package com.renthouse.billing;
import com.renthouse.auth.*;import com.renthouse.common.api.PageResponse;import com.renthouse.common.exception.BusinessException;import com.renthouse.common.id.SnowflakeIdGenerator;import java.time.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class BillingService{private final JdbcTemplate j;private final SnowflakeIdGenerator ids;public BillingService(JdbcTemplate j,SnowflakeIdGenerator ids){this.j=j;this.ids=ids;}
 @Transactional public BillView create(long contractId,Create c){CurrentUser.requireRole(UserRole.LANDLORD);long landlord=CurrentUser.require().id();long[] x=j.query("SELECT tenant_id,landlord_id FROM tenancy_contract WHERE id=? AND landlord_id=? AND status IN ('ACTIVE','CHECKOUT_PENDING')",r->r.next()?new long[]{r.getLong(1),r.getLong(2)}:null,contractId,landlord);if(x==null)throw new BusinessException("CONTRACT_NOT_BILLABLE","合同不可出账",HttpStatus.CONFLICT);long id=ids.nextId();LocalDateTime n=LocalDateTime.now();j.update("INSERT INTO bill(id,bill_no,contract_id,tenant_id,landlord_id,bill_type,period_start,period_end,amount_cent,due_date,status,remark,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,'PENDING_PAYMENT',?,?,?)",id,"ZD"+id,contractId,x[0],x[1],c.billType(),c.periodStart(),c.periodEnd(),c.amountCent(),c.dueDate(),c.remark(),n,n);return find(id);}
 public PageResponse<BillView> list(int page,int size){AuthenticatedUser u=CurrentUser.require();page=Math.max(1,page);size=Math.min(50,Math.max(1,size));String c=u.role()==UserRole.LANDLORD?"landlord_id":"tenant_id";Long t=j.queryForObject("SELECT COUNT(*) FROM bill WHERE "+c+"=?",Long.class,u.id());return PageResponse.of(j.query("SELECT * FROM bill WHERE "+c+"=? ORDER BY due_date DESC LIMIT ? OFFSET ?",(r,n)->map(r),u.id(),size,(page-1)*size),t==null?0:t,page,size);}
 @Transactional public BillView report(long id,Report r){CurrentUser.requireRole(UserRole.TENANT);BillView b=find(id);if(Long.parseLong(b.tenantId())!=CurrentUser.require().id()||!"PENDING_PAYMENT".equals(b.status()))throw new BusinessException("PAYMENT_REPORT_INVALID","账单当前不可报备",HttpStatus.CONFLICT);long rid=ids.nextId();LocalDateTime n=LocalDateTime.now();j.update("INSERT INTO bill_payment_report(id,bill_id,tenant_id,voucher_url,paid_amount_cent,paid_at,note,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'PENDING_VERIFICATION',?,?)",rid,id,CurrentUser.require().id(),r.voucherUrl(),r.amountCent(),r.paidAt(),r.note(),n,n);j.update("UPDATE bill SET status='PENDING_VERIFICATION',updated_at=? WHERE id=?",n,id);return find(id);}
 @Transactional public BillView verify(long id,boolean approved){CurrentUser.requireRole(UserRole.LANDLORD);BillView b=find(id);if(Long.parseLong(b.landlordId())!=CurrentUser.require().id()||!"PENDING_VERIFICATION".equals(b.status()))throw new BusinessException("PAYMENT_VERIFY_INVALID","账单当前不可核销",HttpStatus.CONFLICT);LocalDateTime n=LocalDateTime.now();j.update("UPDATE bill SET status=?,verified_at=?,verifier_id=?,paid_at=?,updated_at=? WHERE id=?",approved?"PAID":"PENDING_PAYMENT",approved?n:null,approved?CurrentUser.require().id():null,approved?n:null,n,id);j.update("UPDATE bill_payment_report SET status=?,updated_at=? WHERE bill_id=? AND status='PENDING_VERIFICATION'",approved?"VERIFIED":"REJECTED",n,id);return find(id);}
 public BillView find(long id){AuthenticatedUser u=CurrentUser.require();return j.query("SELECT * FROM bill WHERE id=? AND (tenant_id=? OR landlord_id=?)",r->{if(!r.next())throw new BusinessException("BILL_NOT_FOUND","账单不存在",HttpStatus.NOT_FOUND);return map(r);},id,u.id(),u.id());}
 private BillView map(java.sql.ResultSet r)throws java.sql.SQLException{return new BillView(""+r.getLong("id"),r.getString("bill_no"),""+r.getLong("contract_id"),""+r.getLong("tenant_id"),""+r.getLong("landlord_id"),r.getString("bill_type"),r.getInt("amount_cent"),r.getDate("due_date").toLocalDate(),r.getString("status"),r.getTimestamp("paid_at")==null?null:r.getTimestamp("paid_at").toLocalDateTime(),r.getTimestamp("verified_at")==null?null:r.getTimestamp("verified_at").toLocalDateTime(),r.getString("remark"));}
 public record Create(String billType,LocalDate periodStart,LocalDate periodEnd,int amountCent,LocalDate dueDate,String remark){} public record Report(String voucherUrl,int amountCent,LocalDateTime paidAt,String note){}
}
