<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import ModalShell from '../components/ModalShell.vue'
import { useRentalStore } from '../stores/rental'
const route = useRoute(); const router = useRouter(); const store = useRentalStore(); const appointmentOpen = ref(false)
const house = computed(() => store.getHouse(Number(route.params.houseId))); const favorite = computed(() => !!house.value && store.favorites.includes(house.value.id))
const price = computed(() => house.value ? store.price(house.value) : 0); const yuan = (amount: number) => (amount / 100).toLocaleString('zh-CN')
function back() { router.back() }; function book() { appointmentOpen.value = true }; function submitAppointment() { if (house.value) { store.bookViewing(house.value.id, '本周六 (2026-08-01)', '14:00 - 15:00'); appointmentOpen.value = false; router.push(`/messages/${house.value.id}`) } }
onMounted(() => { if (!house.value) router.replace('/home') })
</script>
<template><section v-if="house" class="detail-page"><button class="detail-back" @click="back">‹</button><div class="detail-gallery"> <template v-for="item in house.media" :key="item.url"><video v-if="item.type === 'video'" :src="item.url" :poster="item.poster" controls muted autoplay loop playsinline></video><img v-else :src="item.url" alt="房源实拍" /></template></div><article class="detail-card"><h1>{{ house.name }}</h1><div class="detail-price"><strong>¥{{ yuan(price) }}</strong><span>/月</span><small>浏览 97 · 发布于 07-21</small></div><div class="detail-facts"><div><b>{{ house.type }}</b><span>类型</span></div><div><b>{{ house.layout.split('·')[0] }}</b><span>户型</span></div><div><b>{{ house.layout.split('·')[1] }}</b><span>使用面积</span></div><div><b>房东直签</b><span>和谁签约</span></div><div><b>押1付1</b><span>付款方式</span></div><div><b>半年起租</b><span>最短租期</span></div></div><div class="detail-tags"><span v-for="tag in house.tags" :key="tag">{{ tag }}</span><span>不限性别</span><span>随时入住</span></div><section><h2>设施</h2><div class="facility-grid"><div v-for="item in ['空调','衣柜','椅子','桌子','床','沙发','电梯','油烟机','冰箱','淋浴','洗衣机','热水器']" :key="item" :class="{ unavailable: !house.amenities.includes(item) }"><b>{{ item === '空调' ? '❄️' : item === '洗衣机' ? '🧺' : '◻' }}</b><span>{{ item }}</span></div></div></section><section><h2>描述</h2><h3>居住体验</h3><p>{{ house.description }}</p><h3>房屋来源</h3><p>自己的房子，房东直租没有中介费。可以直接在平台联系我或者线下签约。</p><h3>周边配置</h3><p>交通方便，生活便利，楼下有多家生鲜超市和菜市场。</p></section><div class="score-card"><b>房源评分</b><strong>★ 8.8</strong></div></article><footer class="detail-actions"><button @click="store.toggleFavorite(house.id)">{{ favorite ? '♥ 已收藏' : '♡ 收藏' }}</button><button @click="router.push(`/messages/${house.id}`)">聊一下</button><button @click="store.notify('正在拨号...')">打电话</button><button class="primary" @click="book">预约看房</button></footer><ModalShell v-if="appointmentOpen" @close="appointmentOpen = false"><h2>📅 预约看房时段</h2><label>日期<select><option>本周六 (2026-08-01)</option></select></label><label>时间段<select><option>14:00 - 15:00</option></select></label><button class="modal-primary" @click="submitAppointment">确认发送看房预约</button></ModalShell></section></template>
