package com.renthouse.operation;
import com.renthouse.auth.*;import com.renthouse.common.api.*;import com.renthouse.common.exception.BusinessException;import com.renthouse.common.id.SnowflakeIdGenerator;import jakarta.validation.*;import jakarta.validation.constraints.*;import java.time.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/v1/landlord/listings") public class LandlordListingController{private final JdbcTemplate j;private final SnowflakeIdGenerator ids;public LandlordListingController(JdbcTemplate j,SnowflakeIdGenerator ids){this.j=j;this.ids=ids;}private long owner(){CurrentUser.requireRole(UserRole.LANDLORD);return CurrentUser.require().id();}
 @PostMapping public ApiResponse<Item>create(@RequestBody @Valid Create r){long o=owner();Integer ok=j.queryForObject("SELECT COUNT(*) FROM property_unit WHERE id=? AND landlord_id=?",Integer.class,r.unitId(),o);if(ok==null||ok==0)throw new BusinessException("UNIT_NOT_FOUND","房屋不存在或无权操作",HttpStatus.NOT_FOUND);long id=ids.nextId();LocalDateTime n=LocalDateTime.now();j.update("INSERT INTO house_listing(id,unit_id,landlord_id,title,community_name,district,address,rent_cent,deposit_cent,payment_cycle,publish_status,is_special,special_sort,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'MONTHLY','DRAFT',0,0,?,?)",id,r.unitId(),o,r.title(),r.communityName(),r.district(),r.address(),r.rentCent(),r.depositCent(),n,n);return ApiResponse.ok(new Item(""+id,r.title(),r.rentCent(),"DRAFT",false,"VACANT"));}
 @GetMapping public ApiResponse<PageResponse<Item>>list(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size){long o=owner();page=Math.max(1,page);size=Math.min(50,Math.max(1,size));Long t=j.queryForObject("SELECT COUNT(*) FROM house_listing WHERE landlord_id=?",Long.class,o);return ApiResponse.ok(PageResponse.of(j.query("SELECT l.id,l.title,l.rent_cent,l.publish_status,l.is_special,u.occupancy_status FROM house_listing l JOIN property_unit u ON u.id=l.unit_id WHERE l.landlord_id=? ORDER BY l.updated_at DESC LIMIT ? OFFSET ?",(r,n)->new Item(""+r.getLong(1),r.getString(2),r.getInt(3),r.getString(4),r.getBoolean(5),r.getString(6)),o,size,(page-1)*size),t==null?0:t,page,size));}
 @PostMapping("/{id}/publish")public ApiResponse<Void>publish(@PathVariable long id){long o=owner();int n=j.update("UPDATE house_listing l JOIN property_unit u ON u.id=l.unit_id SET l.publish_status='PUBLISHED',l.published_at=?,l.updated_at=? WHERE l.id=? AND l.landlord_id=? AND u.occupancy_status='VACANT'",LocalDateTime.now(),LocalDateTime.now(),id,o);if(n==0)throw new BusinessException("LISTING_NOT_PUBLISHABLE","房源不存在、无权操作或当前不可发布",HttpStatus.CONFLICT);return ApiResponse.ok();}
 @PostMapping("/{id}/offline")public ApiResponse<Void>offline(@PathVariable long id){int n=j.update("UPDATE house_listing SET publish_status='OFFLINE',offline_at=?,updated_at=? WHERE id=? AND landlord_id=?",LocalDateTime.now(),LocalDateTime.now(),id,owner());if(n==0)throw new BusinessException("LISTING_NOT_FOUND","房源不存在或无权操作",HttpStatus.NOT_FOUND);return ApiResponse.ok();}
 @PatchMapping("/{id}/special")public ApiResponse<Void>special(@PathVariable long id,@RequestBody @Valid Special r){int n=j.update("UPDATE house_listing SET is_special=?,special_sort=?,updated_at=? WHERE id=? AND landlord_id=?",r.enabled(),r.sort(),LocalDateTime.now(),id,owner());if(n==0)throw new BusinessException("LISTING_NOT_FOUND","房源不存在或无权操作",HttpStatus.NOT_FOUND);return ApiResponse.ok();}
 @PostMapping("/{id}/media")public ApiResponse<Void>media(@PathVariable long id,@RequestBody @Valid Media r){long o=owner();Integer n=j.queryForObject("SELECT COUNT(*) FROM house_listing WHERE id=? AND landlord_id=?",Integer.class,id,o);if(n==null||n==0)throw new BusinessException("LISTING_NOT_FOUND","房源不存在或无权操作",HttpStatus.NOT_FOUND);j.update("INSERT INTO listing_media(id,listing_id,media_type,url,cover_url,sort_no,created_at) VALUES(?,?,?,?,?,?,?)",ids.nextId(),id,r.type(),r.url(),r.coverUrl(),r.sort(),LocalDateTime.now());return ApiResponse.ok();}
 public record Item(String id,String title,int rentCent,String publishStatus,boolean special,String occupancyStatus){}public record Create(@Positive long unitId,@NotBlank String title,@NotBlank String communityName,@NotBlank String district,@NotBlank String address,@Positive int rentCent,@PositiveOrZero int depositCent){}public record Special(boolean enabled,@Min(0)int sort){}public record Media(@NotBlank String type,@NotBlank String url,String coverUrl,@Min(0)int sort){}
}
